### PR TITLE
Fix paths in phpstan.neon

### PR DESCRIPTION
**Pull request by szepeviktor**
Everyone puts "level" first but file selection comes first!

### CODE REVIEW

**Comment by szepeviktor** [comment]
We've got work to do 🧑‍🏭 

```
 ------ ---------------------------------------------------------------------- 
  Line   src/Data/Factory/MRZDataFactory.php                                   
 ------ ---------------------------------------------------------------------- 
  8      Method PrinsFrank\MRTD\Data\Factory\MRZDataFactory::fromString() has  
         no return type specified.                                             
 ------ ---------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------- 
  Line   src/MRZ/Provider/MRZObjectProvider.php                                
 ------ ---------------------------------------------------------------------- 
  16     Method PrinsFrank\MRTD\MRZ\Provider\MRZObjectProvider::getMRZTypes()  
         should return array<PrinsFrank\MRTD\MRZ\MRZInterface> but returns     
         array<int, string>.                                                   
 ------ ---------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------- 
  Line   src/MRZParser.php                                                    
 ------ --------------------------------------------------------------------- 
  34     Parameter #2 $length of function str_split expects int<1, max>, int  
         given.                                                               
 ------ --------------------------------------------------------------------- 
```

**Comment by szepeviktor** [comment]
Started adding PHP generics ...

**Comment by PrinsFrank** [comment]
Hey man, sorry, I was already fixing this, should be working now!

**Comment by szepeviktor** [comment]
Too late 😢 https://github.com/PrinsFrank/MRTD/commit/7d69ab4838d20d9ff7f6caefce89ec374f003ccd

**Comment by szepeviktor** [comment]
You may call `TDAta` `TMRZData` ...

**Comment by PrinsFrank** [comment]
@szepeviktor feel free to open a PR if you want! I added you on linkedIn FYI if you want to chat. ;)

**Pull request closed without merging**
