### PR TITLE
Put a link on "Doc series 9303" in README

### PR DESCRIPTION
**Pull request by szepeviktor**
The linked page contains
- more languages
- all parts

### CODE REVIEW

**Comment by PrinsFrank** [comment]
Hey, sorry, I committed in the same lines in the meantime. Can you rebase?

**Comment by szepeviktor** [comment]
Done 🍏

**Comment by PrinsFrank** [comment]
Thanks!!!

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
